name: Nightly Refresh
on:
  schedule:
    - cron: "0 6 * * *"   # 11pm PT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build FAQ pages from CSV
        run: python actions/scripts/build_pages.py
      - name: Commit changes
        run: |
          git config user.name "ghost-bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git commit -m "nightly refresh" || echo "no changes"
      - name: Push
        run: git push
